
CREATE TABLE GMODI.SUPPLYCHAIN_VIZ_2 AS
SELECT 
T1.FULFILL_STORE_KEY,
EXTRACT(YEAR FROM T1.ORDER_DT) AS YR,
T1.ORDER_DT,
T1.ORDER_QTY,
SUBSTR(T2.ZIP5_CD,0,3) AS SOURCE_3,
T6.ORIGIN_ZIP,
T2.ZIP5_CD AS SOURCE,
T4.STATE AS S_STATE,
T5.STATE AS D_STATE,
CONCAT(T4.STATE,T5.STATE) AS PATH,
SUBSTR(T1.SHIP_ZIP5_CD,0,3) AS DESTINATION_3,
T6.DEST_ZIP,
T1.SHIP_ZIP5_CD AS DESTINATION,
T2.REGION_NBR,
T2.LOCATION_NM,
T2.CITY_STATE_NM,
T2.STORE_SQUARE_FOOTAGE_AMT,
T2.IFMX_STORE_NBR,
T2.DISTRICT_NM,
T1.PRODUCT_KEY,
T1.SKU_ID,
T3.IFMX_DEPT_NBR,
T3.IFMX_DEPT_NM,
T3.IFMX_CLASS_NBR,
T3.IFMX_CLASS_NM,
T3.ATG_BRAND_NM,
T3.IFMX_VENDOR_ID,
T3.IFMX_VENDOR_NM,
T6.TRANSIT_TIME_DAYS
FROM 
FINLDM.ORDER_LINE_FCT T1,
FINLDM.STORE_DM T2,
FINLDM.PRODUCT_DM T3,
GMODI.MELISSA_DATA T4,
GMODI.MELISSA_DATA T5,
GMODI.SUPPLY_CHAIN_TRANSIT T6
WHERE
T2.IFMX_STORE_NBR NOT IN ('901') AND
T1.FULFILL_STORE_KEY = T2.STORE_KEY AND 
T1.PRODUCT_KEY = T3.PRODUCT_KEY AND 
T2.ZIP5_CD = T4.ZIP AND 
T1.SHIP_ZIP5_CD = T5.ZIP AND
T1.SHIP_ZIP5_CD > 0  AND 
T6.ORIGIN_ZIP = SUBSTR(T2.ZIP5_CD,0,3) AND T6.DEST_ZIP = SUBSTR(T1.SHIP_ZIP5_CD,0,3) 
;




SELECT * FROM GMODI.SUPPLYCHAIN_VIZ_2;


SELECT 
YR,
IFMX_DEPT_NM, 
IFMX_CLASS_NM, 
SUM(ORDER_QTY) 
FROM 
GMODI.SUPPLYCHAIN_VIZ_2 WHERE  IFMX_DEPT_NBR = '113' AND IFMX_CLASS_NBR = '003'
GROUP BY 
YR,
IFMX_DEPT_NM, 
IFMX_CLASS_NM 
ORDER BY 
YR DESC, 
SUM(ORDER_QTY) DESC; 